### PR TITLE
fix(#144): Deno 1.16 support

### LINKED ISSUE #144: Nothing works with Deno 1.16.0
**Describe the bug** 
Nothing works with Deno 1.16.0

**To Reproduce**
1\. Install or update to Deno 1.16.0
2. deno install -qAf --unstable https://deno.land/x/denon@2.4.9/denon.ts
3. I get the following error

```console
$ deno install -qAf --unstable https://deno.land/x/denon@2.4.9/denon.ts
error: TS2339 [ERROR]: Property 'signal' does not exist on type 'typeof Deno'. 'Deno.signal' is an unstable API. Did you forget to run with the '--unstable' flag?
          await Deno.signal(s);
                     ~~~~~~
    at https://deno.land/x/denon@2.4.9/src/daemon.ts:157:22
```

**Setup**

- OS: windows
- Deno version: 1.16.0
- Denon version: 2.4.9

**Additional context**
This issue is probably due to the following changes in 1.16.0:
https://deno.com/blog/v1.16#new-unstable-signal-listener-api

### PR DESCRIPTION
**Pull request by kamekyame**
Fix #144 

Changed from `Deno.signal` to use `Deno.addSignalListener`.

I didn't understand why I surrounded this part with `Promise.all`, but I changed it to a synchronization function because I thought it was unnecessary by `addSignalListener`.

### CODE REVIEW

**Comment by eliassjogreen** [comment]
LGTM

**Comment by FutureDrivenDev** [comment]
Hey, I just got this error trying to install denon from deno.land:

```
➜  futuredriven.dev git:(main) ✗ deno install -qAf --unstable https://deno.land/x/denon/denon.ts

error: TS2339 [ERROR]: Property 'addSignalListener' does not exist on type 'typeof Deno'. 'Deno.addSignalListener' is an unstable API. Did you forget to run with the '--unstable' flag?
        Deno.addSignalListener(s, () => {
             ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/denon@2.5.0/src/daemon.ts:156:14
```

Seems related?

**Comment by FutureDrivenDev** [comment]
BTW I found out what was happening... 

I was running `deno install` in a directory which contains a `deno.json` file with this:

```
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "https://esm.sh/nano-jsx@v0.0.29/lib",
    "lib": ["dom", "dom.asynciterable", "dom.iterable", "deno.ns", "esnext"]
  }
}
```

So the typescript config never got the `"deno.unstable"` lib. Once I've added that, installation worked normally. D'oh!

BTW I found that out by using `-L debug` and noticing the `lib` here:

```
DEBUG TS - {"allowJs":true,"allowSyntheticDefaultImports":true,"experimentalDecorators":true,"incremental":true,"jsx":"react-jsx","isolatedModules":true,"lib":["dom","dom.asynciterable","dom.iterable","deno.ns","esnext"],"module":"esnext","resolveJsonModule":true,"strict":true,"target":"esnext","tsBuildInfoFile":"deno:///.tsbuildinfo","useDefineForClassFields":true,"useUnknownInCatchVariables":false,"emitDecoratorMetadata":false,"importsNotUsedAsValues":"remove","inlineSourceMap":true,"inlineSources":true,"outDir":"deno://","removeComments":true,"jsxImportSource":"https://esm.sh/nano-jsx@v0.0.29/lib"}
```
