### ISSUE TITLE
Denon get Error TS2339 on start/download etc. since upgrading to deno v1.7.0

### ISSUE THREAD

**Issue by MarvinGronhorst** [denosaurs/denon#122]
**Describe the bug**
After updating to deno v1.7.0 and trying to run a script with denon i get the following error messages (2 Errors): 

error: TS2339 [ERROR]: Property 'url' does not exist on type 'NetPermissionDescriptor'.
              return pd.url
                        ~~~
    at https://deno.land/std@0.74.0/permissions/mod.ts:17:25

TS2339 [ERROR]: Property 'url' does not exist on type 'NetPermissionDescriptor'.
                ? `--allow-${pd.name}=${pd.url}`
                                           ~~~
    at https://deno.land/std@0.74.0/permissions/mod.ts:18:44

Then i tried to remove the denon script from $Home/.deno and reinstalling the new 2.4.6 version, but i got the same message: 

taskman-deno$ deno install -A -f --unstable https://deno.land/x/denon@2.4.4/denon.ts

Check https://deno.land/x/denon@2.4.4/denon.ts
error: TS2339 [ERROR]: Property 'url' does not exist on type 'NetPermissionDescriptor'.
              return pd.url
                        ~~~
    at https://deno.land/std@0.74.0/permissions/mod.ts:17:25

TS2339 [ERROR]: Property 'url' does not exist on type 'NetPermissionDescriptor'.
                ? `--allow-${pd.name}=${pd.url}`
                                           ~~~
    at https://deno.land/std@0.74.0/permissions/mod.ts:18:44

Found 2 errors.                                                                   
taskman-deno$ deno install -qAf --unstable https://x.nest.land/denon/denon.ts

error: Import 'https://x.nest.land/denon/denon.ts' failed: 404 Not Found

**To Reproduce**
1. Run a denon-script after updating deno version to v1.7.0
2. Install denon after updating to deno version to v1.7.0

**Expected behavior**
Running the script or installing the denon version 

**Setup**

- OS: macOS 11.1
- Deno version: deno 1.7.0 (release, x86_64-apple-darwin)
v8 8.9.255.3
typescript 4.1.3
- Denon version: 2.4.4 (i think, i removed it to try and fix it with a "try to turn it off and on again") 

**Additional info** 
Tried to install another script with the same flags (-qAf) and it worked. Script was udd. The installscript in the deno manual works too. 
Replicating the issue on another machine lead to the same error

**Comment by eliassjogreen** [comment]
Try installing again with a `-r` flag to reload as 2.4.6 is the latest version of denon, also you might want to use deno.land/x instead as it isn't released on nest yet...

**Comment by MarvinGronhorst** [comment]
Thanks for the quick reply! sadly the reload did not work. 

```bash
$ deno install -qAf -r --unstable https://deno.land/x/denon/denon.ts

Warning Implicitly using latest version (2.4.6) for https://deno.land/x/denon/denon.ts
error: TS2339 [ERROR]: Property 'url' does not exist on type 'NetPermissionDescriptor'.
              return pd.url
                        ~~~
    at https://deno.land/std@0.83.0/permissions/mod.ts:17:25

TS2339 [ERROR]: Property 'url' does not exist on type 'NetPermissionDescriptor'.
                ? `--allow-${pd.name}=${pd.url}`
                                           ~~~
    at https://deno.land/std@0.83.0/permissions/mod.ts:18:44

Found 2 errors.
```

**Comment by Forwardslash-development** [comment]
Same issue as above.  Deno 1.7.0/Typescript 4.1.3/v8 8.9.255.3

**Comment by hokkqi** [comment]
Getting the same Error

```
deno 1.7.0 (release, x86_64-pc-windows-msvc)
v8 8.9.255.3
typescript 4.1.3
```

![image](https://user-images.githubusercontent.com/20520193/106020440-0e9da100-60c4-11eb-8986-49b011d325fe.png)

**Comment by esh2n** [comment]
Also same error(in Mac)

```
deno 1.7.0 (release, x86_64-apple-darwin)
v8 8.9.255.3
typescript 4.1.3
```

![スクリーンショット 2021-01-29 14 45 51](https://user-images.githubusercontent.com/55518345/106236685-b9d36500-6240-11eb-8e47-b81a023d8cd4.png)

**Comment by hu-qi** [comment]
The same:
```
TS2339 [ERROR]: Property 'url' does not exist on type 'NetPermissionDescriptor'.
                ? `--allow-${pd.name}=${pd.url}`
                                           ~~~
    at https://deno.land/std@0.83.0/permissions/mod.ts:18:44
````
How did you guys fix it? Thanks!

**Comment by esh2n** [comment]
@hu-qi 
I have not solve this yet. 
What I can do is only downgrade deno versions to 1.5.2.

**Comment by patrickgamer** [comment]
I've downgraded to v1.6.3 and seems to work

**Comment by MarvinGronhorst** [comment]
> I've downgraded to v1.6.3 and seems to work

Yes this works, this error exists because of breaking changes introduced in Deno 1.7.0 and its STD 0.84. 

The PR #124 fixes this issue, as #123 ist a duplicate of this issue here. 

So i will close this issue, as it has been resolved in #124

**Comment by luxwarp** [comment]
Since deno.land does not have the fix yet you can install denon from github with 
`deno install -qAf --unstable https://raw.githubusercontent.com/denosaurs/denon/main/denon.ts `

**Comment by dogukanakkaya** [comment]
I already had the latest versions of deno yet
```
deno upgrade
```
worked for me.

**Comment by BishopX312** [comment]
How do you downgrade?
-- I cant seem to find the documentation
