### ISSUE TITLE
Nothing works with Deno 1.16.0

### ISSUE THREAD

**Issue by kamekyame** [denosaurs/denon#144]
**Describe the bug** 
Nothing works with Deno 1.16.0

**To Reproduce**
1\. Install or update to Deno 1.16.0
2. deno install -qAf --unstable https://deno.land/x/denon@2.4.9/denon.ts
3. I get the following error

```console
$ deno install -qAf --unstable https://deno.land/x/denon@2.4.9/denon.ts
error: TS2339 [ERROR]: Property 'signal' does not exist on type 'typeof Deno'. 'Deno.signal' is an unstable API. Did you forget to run with the '--unstable' flag?
          await Deno.signal(s);
                     ~~~~~~
    at https://deno.land/x/denon@2.4.9/src/daemon.ts:157:22
```

**Setup**

- OS: windows
- Deno version: 1.16.0
- Denon version: 2.4.9

**Additional context**
This issue is probably due to the following changes in 1.16.0:
https://deno.com/blog/v1.16#new-unstable-signal-listener-api

**Comment by ralyodio** [comment]
same on linux

**Comment by AmmadEteam** [comment]
Same here I am also getting this error with deno version 1.16.1.
is there any way to resolve this issue.

**Comment by kamekyame** [comment]
I don't have a detailed understanding of denon's code, but I've created a PR( #145 ) that has been modified to work.
If a temporary solution is fine, use my forked denon.

```
deno install -qAf --unstable https://raw.githubusercontent.com/kamekyame/denon/main/denon.ts
```

**Comment by nnmrts** [comment]
Thanks for the fork @kamekyame! As https://github.com/denosaurs/denon/issues/126 mentioned, it's probably also a good idea to use `SIGTERM` instead of `SIGKILL`, especially because Deno (or actually Rust) doesn't allow listening for `SIGKILL`. I'll fork your fork changing that as well real quick.
